
version: '3.7'
services:
  database:
    image: postgres:14.4
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pgdata:

    
